// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var React = require("react");
var Js_dict = require("rescript/lib/js/js_dict.js");
var Js_json = require("rescript/lib/js/js_json.js");
var Js_array = require("rescript/lib/js/js_array.js");
var Js_string = require("rescript/lib/js/js_string.js");
var Belt_Array = require("rescript/lib/js/belt_Array.js");
var Js_promise = require("rescript/lib/js/js_promise.js");
var Belt_Option = require("rescript/lib/js/belt_Option.js");
var Caml_option = require("rescript/lib/js/caml_option.js");
var Webapi__Fetch = require("rescript-webapi/src/Webapi/Webapi__Fetch.bs.js");

require('./styles.css')
;

var $$document = document;

function addEventListener(prim0, prim1, prim2) {
  prim0.addEventListener(prim1, prim2);
}

function setInnerHTML(prim0, prim1) {
  prim0.innerHTML = prim1;
}

function getElementById(prim0, prim1) {
  return Caml_option.nullable_to_opt(prim0.getElementById(prim1));
}

function Component(Props) {
  var match = React.useState(function () {
        return "";
      });
  var setSearchText = match[1];
  var searchText = match[0];
  var match$1 = React.useState(function () {
        return [];
      });
  var setSearchProducts = match$1[1];
  var match$2 = React.useState(function () {
        return 0;
      });
  var setCount = match$2[1];
  React.useEffect((function () {
          var request = Webapi__Fetch.RequestInit.make(/* Get */0, {
                  Accept: "*/*",
                  "Content-type": "application/json"
                }, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined)(undefined);
          var __x = fetch(Js_string.concat(searchText, "/product?name="), request);
          var __x$1 = Js_promise.then_((function (prim) {
                  return prim.json();
                }), __x);
          var __x$2 = Js_promise.then_((function (json) {
                  return Promise.resolve(Belt_Option.getExn(Js_json.decodeArray(json)));
                }), __x$1);
          Js_promise.then_((function (array) {
                  var t = Js_array.map((function (x) {
                          var obj = Belt_Option.getExn(Js_json.decodeObject(x));
                          return {
                                  name: Belt_Option.getExn(Belt_Option.flatMap(Js_dict.get(obj, "name"), Js_json.decodeString)),
                                  price: Belt_Option.getExn(Belt_Option.flatMap(Js_dict.get(obj, "price"), Js_json.decodeNumber)) | 0
                                };
                        }), array);
                  Curry._1(setSearchProducts, (function (param) {
                          return t;
                        }));
                  return Promise.resolve(t);
                }), __x$2);
          return (function (param) {
                    
                  });
        }), [match$2[0]]);
  var elements = Belt_Array.map(match$1[0], (function (x) {
          return React.createElement("div", undefined, React.createElement("div", {
                          className: "product"
                        }, React.createElement("p", undefined, x.name)), React.createElement("div", {
                          className: "price"
                        }, React.createElement("p", undefined, String(x.price))));
        }));
  var onClick = function (_evt) {
    Curry._1(setCount, (function (prev) {
            return prev + 1 | 0;
          }));
  };
  return React.createElement("div", {
              id: "container"
            }, React.createElement("h2", undefined, "Product Search"), React.createElement("label", {
                  htmlFor: "product-text"
                }, "Enter search text:"), React.createElement("input", {
                  id: "product-text",
                  type: "text",
                  onChange: (function (e) {
                      var text = e.target.value;
                      Curry._1(setSearchText, (function (param) {
                              return text;
                            }));
                    })
                }), React.createElement("button", {
                  onClick: onClick
                }, "Search"), elements);
}

var getExn = Belt_Option.getExn;

var flatMap = Belt_Option.flatMap;

var make = Component;

exports.getExn = getExn;
exports.flatMap = flatMap;
exports.$$document = $$document;
exports.addEventListener = addEventListener;
exports.setInnerHTML = setInnerHTML;
exports.getElementById = getElementById;
exports.make = make;
/*  Not a pure module */
